spring.application.name=pkdev-demo1
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
info.app.name=Devops demo1
info.app.version=1.0.0
info.app.owner=Prashant
management.info.env.enabled=true