all:
  hosts:
    demo1-server:
      ansible_host: 18.234.172.82
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/pkdev-tata-key
      ansible_python_interpreter: /usr/bin/python3